[phases.setup]
nixPkgs = ["python39", "nodejs-20_x"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && chmod +x install.sh && ./install.sh",
    "python download_model.py",
    "cd frontend && npm install --production=false",
    "cd frontend && npm run build"
]

[start]
cmd = "python app.py" 